services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: db-personas
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gestion_personas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  # Backend Flask
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: despliegue-backend:latest
    container_name: backend-personas
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: despliegue-frontend:latest
    container_name: frontend-personas
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
